### ISSUE TITLE
The jx-intro.ova file is not present on the Dropdown URL

### ISSUE THREAD

**Issue by stabenfeldt** [brentlaster/safaridocs#2]
Hi,

I'm attending your Getting Started with Jenins-X course.

> Prior to the class, you will need to download the virtual machine image: https://www.dropbox.com/s/kmae9ghgdoihxis/jx-intro.ova?dl=0

The VirtualBox image does not exist on the server anymore. 
Can you give me an updated URL to the image?

Cheers,
Martin

**Comment by stabenfeldt** [comment]
I found the updated URL in the group chat.
Case closed for now. I guess you'll update the slides when you have the time. :-)

**Comment by aaron88alford** [comment]
Martin, good morning and great start to rogue. Would you mind sharing the URL with us so as not to get confused? That way we will all be ready when class starts.

Thanks a lot
Aaron

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stabenfeldt** [comment]
Yes of course! :-)
The correct URL for the virtual machine image is: https://www.dropbox.com/s/0tmsfgxgwhafymp/jx-intro.ova?dl=0
